Repository ucbds-infra/otter-grader, pull requests merged in 2022-10, with the labels that each got.

#533 Display emojis with test results
  CHANGELOG.md
  otter/test_files/abstract_test.py
  otter/test_files/exception_test.py
  otter/test_files/ok_test.py
  test/test_check.py
  test/test_notebook.py
  test/test_run.py
Labels: enhancement

#532 Allow users to specify Python versions
  CHANGELOG.md
  docs/otter_assign/v1/notebook_format.rst
  docs/workflow/otter_generate/container_image.rst
  otter/assign/assignment.py
  otter/assign/utils.py
  otter/cli.py
  otter/generate/__init__.py
  otter/generate/templates/python/environment.yml
  otter/generate/templates/r/environment.yml
  test/test-assign/example-autograder-correct/environment.yml
  test/test-assign/example.ipynb
Labels: enhancement

#547 Round results point values to 5 decimal places
  CHANGELOG.md
  otter/test_files/__init__.py
  test/test-run/autograder/source/tests/q4.py
Labels: bug

#545 Add example notebook for exception-based tests
  examples/data-88e-proj03-exception/README.md
  examples/data-88e-proj03-exception/defaults.csv
  examples/data-88e-proj03-exception/proj03.ipynb
Labels: documentation

#546 Clearer PDF generation failures
  CHANGELOG.md
  docs/workflow/executing_submissions/gradescope.rst
  docs/workflow/otter_generate/images/pdf_generation_failed_gs.png
  docs/workflow/otter_generate/index.rst
  otter/export/exporters/__init__.py
  otter/export/exporters/base_exporter.py
  otter/export/exporters/via_latex.py
  otter/run/__init__.py
  otter/run/run_autograder/autograder_config.py
  otter/run/run_autograder/runners/abstract_runner.py
  otter/run/run_autograder/runners/python_runner.py
  otter/run/run_autograder/runners/r_runner.py
  otter/test_files/__init__.py
  test/test_run.py
Labels: enhancement

#549 Add `force_public_test_summary` and make failed public tests display correctly
  CHANGELOG.md
  otter/run/run_autograder/autograder_config.py
  otter/test_files/__init__.py
  test/test_run.py
Labels: bug

#573 Add configuration files for Otter Assign
  CHANGELOG.md
  docs/otter_assign/v1/notebook_format.rst
  otter/assign/assignment.py
  otter/assign/notebook_transformer.py
  test/test-assign/assignment_config.yml
  test/test-assign/exception-example.ipynb
Labels: enhancement
