Repository ucbds-infra/otter-grader, pull requests merged in 2023-07, with the labels that each got.

#650 GradeOverride Plugin
  otter/plugins/builtin/grade_override.py
Labels: bug

#653 fixed bug preventing plugin configurations from coming through in otterer_config.json
  CHANGELOG.md
  otter/assign/__init__.py
  otter/plugins/builtin/grade_override.py
Labels: bug

#651 Allow markdown cells to be used for delim cells
  CHANGELOG.md
  Dockerfile
  docs/otter_assign/notebook_format.rst
  otter/assign/blocks.py
  test/test_assign/files/exception-example.ipynb
Labels: enhancement

#657 Close file handles before docker cp
  otter/grade/containers.py
Labels: bug

#661 Use Otter Grade CLI to override otter_config.json values
  CHANGELOG.md
  otter/cli.py
  otter/grade/__init__.py
  otter/grade/containers.py
  test/conftest.py
  test/test_grade/test_integration.py
Labels: enhancement

#663 Only add seeds to code cells
  otter/execute/preprocessor.py
Labels: bug

#662 Normalize notebooks before write in Otter Assign
  CHANGELOG.md
  otter/assign/notebook_transformer.py
Labels: bug

#664 Added assignment summary to Otter Assign
  CHANGELOG.md
  otter/assign/output.py
  otter/assign/tests_manager.py
Labels: enhancement

#665 Convert from Conda to Mamba
  CHANGELOG.md
  Dockerfile
  bin/run_tests
  otter/generate/__init__.py
  otter/generate/templates/common/run_autograder
  otter/generate/templates/python/setup.sh
  otter/generate/templates/r/setup.sh
  otter/run/run_autograder/autograder_config.py
  test/files/Dockerfile
  test/test_assign/files/example-autograder-correct/run_autograder
  test/test_assign/files/example-autograder-correct/setup.sh
  test/test_assign/files/gs-autograder-correct/run_autograder
  test/test_assign/files/gs-autograder-correct/setup.sh
  test/test_assign/files/rmd-autograder-correct/run_autograder
  test/test_assign/files/rmd-autograder-correct/setup.sh
  test/test_generate/files/autograder-correct/run_autograder
  test/test_generate/files/autograder-correct/setup.sh
  test/test_generate/files/autograder-custom-env/run_autograder
  test/test_generate/files/autograder-custom-env/setup.sh
  test/test_generate/files/autograder-r-correct/run_autograder
  test/test_generate/files/autograder-r-correct/setup.sh
  test/test_generate/files/autograder-r-requirements-correct/run_autograder
  test/test_generate/files/autograder-r-requirements-correct/setup.sh
  test/test_generate/files/autograder-token-correct/run_autograder
  test/test_generate/files/autograder-token-correct/setup.sh
  test/test_grade/test_integration.py
  test/test_run/files/autograder/source/run_autograder
  test/test_run/files/autograder/source/setup.sh
Labels: enhancement

#666 Update documentation for v5
  docs/_static/grading-environment-r.yml
  docs/_static/grading-environment.yml
  docs/_static/python_setup.sh
  docs/_static/r_setup.sh
  docs/conf.py
  docs/execution.rst
  docs/index.rst
  docs/otter_assign/notebook_format.rst
  docs/otter_assign/usage.rst
  docs/resources.rst
  docs/tutorial.rst
  docs/workflow/executing_submissions/index.rst
  docs/workflow/executing_submissions/otter_grade.rst
  docs/workflow/otter_generate/container_image.rst
  docs/workflow/otter_generate/index.rst
Labels: documentation

#667 Change from default python 3.7 to 3.9
  .readthedocs.yml
  CHANGELOG.md
  docs/_static/grading-environment-r.yml
  docs/_static/grading-environment.yml
  docs/conf.py
  docs/otter_assign/notebook_format.rst
  docs/workflow/otter_generate/container_image.rst
  otter/generate/__init__.py
  rtd_environment.yml
  test/test_assign/files/gs-autograder-correct/environment.yml
  test/test_assign/files/rmd-autograder-correct/environment.yml
  test/test_generate/files/autograder-correct/environment.yml
  test/test_generate/files/autograder-r-correct/environment.yml
  test/test_generate/files/autograder-r-requirements-correct/environment.yml
  test/test_generate/files/autograder-token-correct/environment.yml
  test/test_run/files/autograder/source/environment.yml
Labels: enhancement

#673 Add nbconvert as required dependency for non-WASM environments
  CHANGELOG.md
  otter/execute/__init__.py
  requirements.txt
Labels: bug

#670 Improve CI performance
  .github/workflows/run-tests.yml
  Makefile
  test/conftest.py
  test/files/partial-dockerfile.txt
  test/test_grade/test_integration.py
Labels: tech debt

#679 Fix local submission zip check
  CHANGELOG.md
  otter/check/validate_export/__main__.py
Labels: bug

#682 Remove cell ID patch from otter assign
  CHANGELOG.md
  otter/assign/notebook_transformer.py
  otter/assign/utils.py
  test/utils.py
Labels: bug

#675 Add force-save to Otter Assign for R notebooks
  CHANGELOG.md
  otter/assign/assignment.py
  otter/assign/notebook_transformer.py
  otter/assign/r_adapter/cell_factory.py
  otter/generate/__init__.py
  test/test_assign/files/r-correct/autograder/r-example.ipynb
  test/test_assign/files/r-correct/student/r-example.ipynb
  test/test_assign/files/r-example.ipynb
  test/test_assign/files/rmd-autograder-correct/setup.sh
  test/test_generate/files/autograder-r-correct/setup.sh
  test/test_generate/files/autograder-r-requirements-correct/setup.sh
Labels: enhancement

#683 Switch from stable branch to latest tag
  .github/workflows/release.yml
  .github/workflows/run-tests.yml
Labels: tech debt

#684 Add configurable required acknowledgement when a PDF is not included in the submission zip
  CHANGELOG.md
  docs/otter_assign/images/R_assign_sample_question.png
  docs/otter_assign/images/assign_intercell_seeding.png
  docs/otter_assign/images/assign_no_pdf_confirmation.png
  docs/otter_assign/images/assign_sample_code_manual.png
  docs/otter_assign/images/assign_sample_question.png
  docs/otter_assign/images/assign_sample_written_manual.png
  docs/otter_assign/images/assign_sample_written_manual_with_prompt.png
  docs/otter_assign/notebook_format.rst
  otter/assign/assignment.py
  otter/assign/notebook_transformer.py
  otter/assign/utils.py
  otter/check/notebook.py
  otter/check/utils.py
  otter/utils.py
  requirements.txt
  test/test_assign/files/no-pdf-ack-correct/autograder/master-autograder_2023_07_19T22_10_42_167650.zip
  test/test_assign/files/no-pdf-ack-correct/autograder/master.ipynb
  test/test_assign/files/no-pdf-ack-correct/student/master.ipynb
  test/test_assign/files/no-pdf-ack-with-message-correct/autograder/master-autograder_2023_07_19T22_12_54_231593.zip
  test/test_assign/files/no-pdf-ack-with-message-correct/autograder/master.ipynb
  test/test_assign/files/no-pdf-ack-with-message-correct/student/master.ipynb
  test/test_assign/test_integration.py
  test/test_check/test_notebook.py
Labels: enhancement

#685 Add hashes of requirements files to mamba env cache key
  .github/workflows/run-tests.yml
Labels: tech debt
